train_data_file: ./data/processed/europarl/europarl.tokenized.en.split/train/data.txt
valid_data_file: ./data/processed/europarl/europarl.tokenized.en.split/valid/data.txt
test_data_file: ./data/processed/europarl/europarl.tokenized.en.split/test/data.txt
tokenizer_name: ./data/processed/gpt2-europarl-tokenizer
num_train_epochs: 10
block_size: 512
seed: 42
